version: "3.8"
services: 
  api:
    container_name: booking-api
    build: 
      context: .
      dockerfile: api/Dockerfile
    image: booking-api
    restart: always
    environment:
      - ENVIRONMENT=Staging
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - booking_net

  notifier:
    container_name: booking-notifier
    build: 
      context: .
      dockerfile: notifier/Dockerfile
    image: booking-notifier
    restart: always
    environment:
      - ENVIRONMENT=Staging
    depends_on:
      - rabbitmq
    networks:
      - booking_net

  mongodb:
    container_name: booking-db
    image: mongo
    restart: always
    volumes:
      - ./.docker/data:/data/db
    ports:
      - "27017:27017"
    networks:
      - booking_net

  rabbitmq:
    container_name: booking-rabbitmq
    image: rabbitmq:3-management
    restart: always
    volumes: 
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/log/:/var/log/rabbitmq/
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - booking_net

networks:
  booking_net:
    driver: bridge