apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: booking-notifier-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: booking-notifier-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 25
