name: CI-CD

on:
  push:
    branches: [develop]
  workflow_dispatch:

env:
  K8S_NAMESPACE: bookings

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1.9.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push (Booking API)
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: api/Dockerfile
          push: true
          tags: |
            jailtonjunior/booking-api:latest
            jailtonjunior/booking-api:v${{github.run_number}}

      - name: Build and push (Booking Notifier)
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: notifier/Dockerfile
          push: true
          tags: |
            jailtonjunior/booking-notifier:latest
            jailtonjunior/booking-notifier:v${{github.run_number}}

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v2

      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_CONFIG}}

      - name: Deploy Namespace
        uses: Azure/k8s-deploy@v1.3
        with:
          manifests: |
            .k8s/namespaces/bookings-ns.yaml

      - name: Deploy MongoDB
        uses: Azure/k8s-deploy@v1.3
        with:
          namespace: ${{ env.K8S_NAMESPACE }}
          manifests: |
            .k8s/deployments/mongo-dp.yaml
            .k8s/services/mongo-svc.yaml

      - name: Deploy RabbitMQ
        uses: Azure/k8s-deploy@v1.3
        with:
          namespace: ${{ env.K8S_NAMESPACE }}
          manifests: |
            .k8s/deployments/rabbit-dp.yaml
            .k8s/services/rabbit-svc.yaml

      - name: Deploy API
        uses: Azure/k8s-deploy@v1.3
        with:
          namespace: ${{ env.K8S_NAMESPACE }}
          images: jailtonjunior/booking-api:v${{github.run_number}}
          manifests: |
            .k8s/deployments/api-dp.yaml
            .k8s/services/api-svc.yaml

      - name: Deploy Notifier
        uses: Azure/k8s-deploy@v1.3
        with:
          namespace: ${{ env.K8S_NAMESPACE }}
          images: jailtonjunior/booking-notifier:v${{github.run_number}}
          manifests: |
            .k8s/deployments/notifier-dp.yaml
